# Generated by Django 6.0.3 on 2026-04-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='issues/')),
                ('issue_type', models.CharField(choices=[('pothole', 'Pothole'), ('water', 'Water Leak'), ('electricity', 'Electricity Issue'), ('other', 'Other')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
